### ISSUE TITLE
Coreprotect causes Large Chest to dupe on exp

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/WildChests#110]
### Minecraft's Version

1.18.2 Purpur dev 1606

### Plugin's Version

Wildchests-b58

### Describe the bug

On wither explosion of a Large chest it does not break but drops a duplicate chest item when coreprotect is installed.

### To Reproduce

Place a Large chest
Have a wither explode the chest
See duped item drop

### Additional Information

[07:33:10 ERROR]: Could not pass event EntityExplodeEvent to WildChests v2.3.0.57
java.lang.NullPointerException: Cannot invoke "org.bukkit.OfflinePlayer.getName()" because "offlinePlayer" is null
        at com.bgsoftware.wildchests.hooks.CoreProtectHook.recordBlockBreak(CoreProtectHook.java:41) ~[WildChests-2.3.0-b57.jar:?]
        at com.bgsoftware.wildchests.handlers.ProvidersHandler.lambda$notifyChestBreakListeners$6(ProvidersHandler.java:169) ~[WildChests-2.3.0-b57.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.bgsoftware.wildchests.handlers.ProvidersHandler.notifyChestBreakListeners(ProvidersHandler.java:169) ~[WildChests-2.3.0-b57.jar:?]
        at com.bgsoftware.wildchests.listeners.BlockListener.onChestExplode(BlockListener.java:121) ~[WildChests-2.3.0-b57.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1362.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1597]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.Explosion.finalizeExplosion(Explosion.java:335) ~[purpur-1.18.2.jar:git-Purpur-1597]
        at net.minecraft.world.level.Level.explode(Level.java:1124) ~[?:?]
        at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1715) ~[?:?]
        at net.minecraft.world.level.Level.explode(Level.java:1117) ~[?:?]
        at net.minecraft.world.entity.projectile.WitherSkull.onHit(WitherSkull.java:104) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractHurtingProjectile.tick(AbstractHurtingProjectile.java:96) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1217) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:696) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.2.jar:git-Purpur-1597]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:674) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[purpur-1.18.2.jar:git-Purpur-1597]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1597]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1597]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1597]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1597]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
I fixed the error, hopefully it fixes the dupe as well.
Let me know if it still occurs

**Comment by Skizzles** [comment]
> I fixed the error, hopefully it fixes the dupe as well. Let me know if it still occurs

No dupe, no error, no issues! Thank you

Closed
