### ISSUE TITLE
SHOPGUI+ not work as price provider

### ISSUE THREAD

**Issue by EasonChu7** [BG-Software-LLC/WildChests#112]
### Minecraft's Version

1.18.2

### Plugin's Version

Dev builds#59

### Describe the bug

ShopGUI+ not work as a price provider 

### To Reproduce

[07:40:14 ERROR]: BlockEntity threw exception at world:8888,78,-9234
java.lang.NoSuchFieldError: shops
        at com.bgsoftware.wildchests.hooks.PricesProvider_ShopGUIPlus14.lambda$getPrice$0(PricesProvider_ShopGUIPlus14.java:36) ~[WildChests-2.3.0.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at com.bgsoftware.wildchests.hooks.PricesProvider_ShopGUIPlus14.getPrice(PricesProvider_ShopGUIPlus14.java:35) ~[WildChests-2.3.0.jar:?]
        at com.bgsoftware.wildchests.handlers.ProvidersHandler.getPrice(ProvidersHandler.java:88) ~[WildChests-2.3.0.jar:?]
        at com.bgsoftware.wildchests.handlers.ProvidersHandler.canSellItem(ProvidersHandler.java:108) ~[WildChests-2.3.0.jar:?]
        at com.bgsoftware.wildchests.utils.ChestUtils.trySellItem(ChestUtils.java:119) ~[WildChests-2.3.0.jar:?]
        at com.bgsoftware.wildchests.utils.ChestUtils.lambda$trySellChest$1(ChestUtils.java:106) ~[WildChests-2.3.0.jar:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at com.bgsoftware.wildchests.utils.ChestUtils.trySellChest(ChestUtils.java:104) ~[WildChests-2.3.0.jar:?]
        at com.bgsoftware.wildchests.nms.NMSInventory_v1_18_R2$TileEntityWildChest.tick(NMSInventory_v1_18_R2.java:362) ~[WildChests-2.3.0.jar:?]
        at com.bgsoftware.wildchests.nms.NMSInventory_v1_18_R2$TileEntityWildChest.tick(NMSInventory_v1_18_R2.java:168) ~[WildChests-2.3.0.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1207) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:917) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:682) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[paper-1.18.2.jar:git-Paper-324]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-324]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-324]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-324]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-324]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
Update WC to latest dev build
