### ISSUE TITLE
Server Crash upon WildChest interaction

### ISSUE THREAD

**Issue by tgmm82** [BG-Software-LLC/WildChests#125]
### Minecraft's Version

1.19.1

### Plugin's Version

WildChests-2.4.0-b66

### Describe the bug

When I open and then close a WildChest the server crashes.  When I restart the server I get this error in Console:  

[15:10:20 ERROR]: BlockEntity threw exception at world:4647,63,1159
java.lang.NoSuchMethodError: 'net.minecraft.world.item.ItemStack net.minecraft.world.entity.item.EntityItem.h()'
	at com.bgsoftware.wildchests.nms.NMSMappings_v1_19_R1.getItem(NMSMappings_v1_19_R1.java:175) ~[WildChests-2.4.0-b66.jar:?]
	at com.bgsoftware.wildchests.nms.NMSInventory_v1_19_R1$TileEntityWildChest.tick(NMSInventory_v1_19_R1.java:339) ~[WildChests-2.4.0-b66.jar:?]
	at com.bgsoftware.wildchests.nms.NMSInventory_v1_19_R1$TileEntityWildChest.tick(NMSInventory_v1_19_R1.java:168) ~[WildChests-2.4.0-b66.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1233) ~[?:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:878) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:702) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1552) ~[paper-1.19.1.jar:git-Paper-87]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-87]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-87]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-87]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-87]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

This is my log after my most recent crash: https://pastebin.com/cSQ8YxJM

issue occurs with a linked chest and chunk collector as well

### To Reproduce

Open a WildChest, specifically I have an Auto-Sell Chest, and then close it and the server crashes.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
