### ISSUE TITLE
Sell Chest with economyshopgui do not work

### ISSUE THREAD

**Issue by YusakiDev** [BG-Software-LLC/WildChests#235]
### Minecraft's Version

This server is running Folia version git-Folia-"25ee657" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 25ee657)

### Plugin's Version

2024.1-b45

### Describe the bug

after set to economyshopgui provider it doesnt seems to do anything at all, i can sell only stone (which is default plugin settings)

### To Reproduce

just try to sell something configure by economyshopgui in a chest

**Comment by YusakiDev** [comment]
```
[19:31:29 INFO]: [WildChests] An error occurred while loading shops-bridge hook for EconomyShopGUI
[19:31:29 WARN]: java.lang.reflect.InvocationTargetException
[19:31:29 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
[19:31:29 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[19:31:29 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[19:31:29 WARN]:        at WildChests-2024.1-b45.jar//com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsProvider.createInstanceInternal(ShopsProvider.java:124)
[19:31:29 WARN]:        at WildChests-2024.1-b45.jar//com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsProvider.createInstance(ShopsProvider.java:108)
[19:31:29 WARN]:        at WildChests-2024.1-b45.jar//com.bgsoftware.wildchests.handlers.ProvidersHandler.lambda$registerPricesProvider$8(ProvidersHandler.java:198)
[19:31:29 WARN]:        at java.base/java.util.Optional.flatMap(Optional.java:289)
[19:31:29 WARN]:        at WildChests-2024.1-b45.jar//com.bgsoftware.wildchests.handlers.ProvidersHandler.registerPricesProvider(ProvidersHandler.java:198)
[19:31:29 WARN]:        at WildChests-2024.1-b45.jar//com.bgsoftware.wildchests.handlers.ProvidersHandler.lambda$new$0(ProvidersHandler.java:61)
[19:31:29 WARN]:        at WildChests-2024.1-b45.jar//com.bgsoftware.wildchests.scheduler.FoliaSchedulerImplementation.lambda$scheduleTask$4(FoliaSchedulerImplementation.java:55)
[19:31:29 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179)
[19:31:29 WARN]:        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37)
[19:31:29 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293)
[19:31:29 WARN]:        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148)
[19:31:29 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[19:31:29 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[19:31:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[19:31:29 WARN]: Caused by: java.lang.UnsupportedOperationException
[19:31:29 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535)
[19:31:29 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235)
[19:31:29 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211)
[19:31:29 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175)
[19:31:29 WARN]:        at WildChests-2024.1-b45.jar//com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_EconomyShopGUI.<init>(ShopsBridge_EconomyShopGUI.java:18)
[19:31:29 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[19:31:29 WARN]:        ... 16 mor

```
Error Log here

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if the issue is fixed

**Comment by YusakiDev** [comment]
This is Fixed.
