### ISSUE TITLE
The sell chest become invalid after its owner goes offline. There are problems with the offline selling function related to ExcellentShop.

### ISSUE THREAD

**Issue by Noogear** [BG-Software-LLC/WildChests#256]
### Minecraft's Version

1.21.1-DEV-ver/1.21.1@f75d4f1 (2024-10-26T13:06:54Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3

### Describe the bug
The particles of the sell chest disappear, and the following error is reported every time it is opened by others. The sell chest will become invalid when its owner goes offline, and if the sell chest is also bound with the chunk collection function, it will also become invalid together.

```
[20:37:42 ERROR]: BlockEntity threw exception at oneblock_world:-4789,121,2437
java.lang.NoSuchMethodError: 'su.nightexpress.nexshop.shop.impl.AbstractProductPricer su.nightexpress.nexshop.api.shop.product.VirtualProduct.getPricer()'
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8.getSellPriceFor(ShopsBridge_ExcellentShop4_8.java:119) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.lambda$getSellPrice$4(ShopsBridge_ExcellentShop4_8.java:150) ~[WildChests-2024.3-b59.jar:?]
        at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.getSellPrice(ShopsBridge_ExcellentShop4_8.java:150) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.getSellPrice(ShopsBridge_ExcellentShop4_8.java:143) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.hooks.PricesProvider_ShopsBridgeWrapper.getPrice(PricesProvider_ShopsBridgeWrapper.java:23) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.handlers.ProvidersHandler.getPrice(ProvidersHandler.java:95) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.handlers.ProvidersHandler.canSellItem(ProvidersHandler.java:115) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.utils.ChestUtils.trySellItem(ChestUtils.java:154) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.utils.ChestUtils.trySellChest(ChestUtils.java:141) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.nms.v1_21.inventory.WildChestBlockEntity.tick(WildChestBlockEntity.java:220) ~[WildChests-2024.3-b59.jar:?]
        at WildChests-2024.3-b59.jar/com.bgsoftware.wildchests.nms.v1_21.inventory.WildChestBlockEntity.tick(WildChestBlockEntity.java:51) ~[WildChests-2024.3-b59.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1060) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1459) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:752) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1827) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:525) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1326) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-f75d4f1]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### To Reproduce

The sell chest will become invalid when its owner goes offline, and if the sell chest is also bound with the chunk collection function, it will also become invalid together.

**Comment by OmerBenGera** [comment]
Update to latest dev build.
If it doesnt fix the issue, send me your nexshop version

**Comment by Noogear** [comment]
> Update to latest dev build. If it doesnt fix the issue, send me your ExcellentShop version

OK. I'm trying. I haven't encountered any problems yet.

**Comment by OmerBenGera** [comment]
> > Update to latest dev build. If it doesnt fix the issue, send me your ExcellentShop version
> 
> OK. I'm trying. I haven't encountered any problems yet.

I'll close this for now
If the issue happens again, let me know

**Comment by Noogear** [comment]
```
[01:20:26 ERROR]: BlockEntity threw exception at oneblock_world:-4798,118,2439
java.lang.NoSuchMethodError: 'su.nightexpress.nexshop.shop.impl.AbstractProductPricer su.nightexpress.nexshop.api.shop.product.VirtualProduct.getPricer()'
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8.getSellPriceFor(ShopsBridge_ExcellentShop4_8.java:119) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.lambda$getSellPrice$4(ShopsBridge_ExcellentShop4_8.java:150) ~[WildChests-2024.3-b60.jar:?]
        at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.getSellPrice(ShopsBridge_ExcellentShop4_8.java:150) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.getSellPrice(ShopsBridge_ExcellentShop4_8.java:143) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.hooks.PricesProvider_ShopsBridgeWrapper.getPrice(PricesProvider_ShopsBridgeWrapper.java:23) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.handlers.ProvidersHandler.getPrice(ProvidersHandler.java:95) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.handlers.ProvidersHandler.canSellItem(ProvidersHandler.java:115) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.utils.ChestUtils.trySellItem(ChestUtils.java:154) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.utils.ChestUtils.trySellChest(ChestUtils.java:141) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.nms.v1_21.inventory.WildChestBlockEntity.tick(WildChestBlockEntity.java:220) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.nms.v1_21.inventory.WildChestBlockEntity.tick(WildChestBlockEntity.java:51) ~[WildChests-2024.3-b60.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1060) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1459) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:752) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1827) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:525) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1326) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```
There is still this problem. ExcellentShop 4.11.8.

**Comment by Noogear** [comment]
> > > Update to latest dev build. If it doesnt fix the issue, send me your ExcellentShop version
> > 
> > 
> > OK. I'm trying. I haven't encountered any problems yet.
> 
> I'll close this for now If the issue happens again, let me know

```
[01:20:26 ERROR]: BlockEntity threw exception at oneblock_world:-4798,118,2439
java.lang.NoSuchMethodError: 'su.nightexpress.nexshop.shop.impl.AbstractProductPricer su.nightexpress.nexshop.api.shop.product.VirtualProduct.getPricer()'
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8.getSellPriceFor(ShopsBridge_ExcellentShop4_8.java:119) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.lambda$getSellPrice$4(ShopsBridge_ExcellentShop4_8.java:150) ~[WildChests-2024.3-b60.jar:?]
        at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.getSellPrice(ShopsBridge_ExcellentShop4_8.java:150) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.libs.com.bgsoftware.common.shopsbridge.ShopsBridge_ExcellentShop4_8$BulkTransactionImpl.getSellPrice(ShopsBridge_ExcellentShop4_8.java:143) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.hooks.PricesProvider_ShopsBridgeWrapper.getPrice(PricesProvider_ShopsBridgeWrapper.java:23) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.handlers.ProvidersHandler.getPrice(ProvidersHandler.java:95) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.handlers.ProvidersHandler.canSellItem(ProvidersHandler.java:115) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.utils.ChestUtils.trySellItem(ChestUtils.java:154) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.utils.ChestUtils.trySellChest(ChestUtils.java:141) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.nms.v1_21.inventory.WildChestBlockEntity.tick(WildChestBlockEntity.java:220) ~[WildChests-2024.3-b60.jar:?]
        at WildChests-2024.3-b60.jar/com.bgsoftware.wildchests.nms.v1_21.inventory.WildChestBlockEntity.tick(WildChestBlockEntity.java:51) ~[WildChests-2024.3-b60.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1060) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1459) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:752) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1827) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:525) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1326) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-4cbc1af]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```
There is still this problem. ExcellentShop 4.11.8.

**Comment by Noogear** [comment]
I will go and check what happened at this coordinate later. Wait for my back.

**Comment by Noogear** [comment]
![image](https://github.com/user-attachments/assets/b33f670a-0336-47c7-92ec-3f724d823c9d)
![image](https://github.com/user-attachments/assets/1cfd0af9-132f-4317-ae68-6a82a04c38b2)
I took a look. It's an ordinary sell chest with the ExcellentShop items I set inside, but it can't be sold.

These are all the goods.
[products.zip](https://github.com/user-attachments/files/17598500/products.zip)

**Comment by OmerBenGera** [comment]
I cannot replicate it using ExcellentShop 4.11.9, nightcore 2.7.0.
Please send me your session logs (latest.log)

**Comment by Noogear** [comment]
[2024-11-01-2.log.gz](https://github.com/user-attachments/files/17606492/2024-11-01-2.log.gz)
I have tried the ExcellentShop version 4.11.9 and still have this problem. It is mainly reflected in the disappearance of the particle effect of the sell chest and the failure of the selling function. Not every sell chest has this problem. It occurs randomly.

**Comment by OmerBenGera** [comment]
Interesting.
Please upload your entire ExcellentShop folder and upload it here, I'll try replicating it as well using your exact configuration

**Comment by Noogear** [comment]
[shop.zip](https://github.com/user-attachments/files/17606635/shop.zip)

**Comment by OmerBenGera** [comment]
I cannot replicate it using your setup.
(Btw, I deleted it as you uploaded credentials to your DB)

**Comment by Noogear** [comment]
This is highly random. I have asked the players in the server to pay attention. When it breaks next time, I will ask them to see what operation caused it.

**Comment by Noogear** [comment]
> I cannot replicate it using your setup. Are you able to replicate it on a server with only WildChests and ExcellentShop, using your exact same config files of both plugins?

I consulted the players in the server. There is a speculation that the owner of the sell chest might cause the chest to become invalid after logging out, and then anyone interacting with this chest would generate an error.

**Comment by Noogear** [comment]
I can now be completely sure that the sell chest will become invalid when its owner goes offline, and if the sell chest is also bound with the chunk collection function, it will also become invalid together.

**Comment by Noogear** [comment]
> Check out latest dev build, this should be fixed

Please let me test it for two days to check if it will be fixed. Could you please add a prompt to view its owner when opening the sell chest or display its owner on the title of the chest?

**Comment by Noogear** [comment]
Good job! Thank you!
