### ISSUE TITLE
Corrupt Plugin after restart

### ISSUE THREAD

**Issue by OmnixiaDEV** [BG-Software-LLC/WildChests#265]
### Minecraft's Version

1.21.1

### Plugin's Version

Latest

### Describe the bug

[Mon 11:01:18 INFO  Server/ServerGamePacketListenerImpl] minij0ker issued server command: /wildchests:chests give minij0ker auto_crafter
 
- [Mon 11:01:18 ERROR Minecraft/Commands] Command exception: /wildchests:chests give minij0ker auto_crafter
org.bukkit.command.CommandException: Cannot execute command 'wildchests:chests' in plugin WildChests v2024.4 - plugin is disabled.
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
    at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
    at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
    at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
    at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
    at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
    at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
    at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
    at net.minecraft.commands.Commands.performCommand(Commands.java:350)
    at net.minecraft.commands.Commands.performCommand(Commands.java:337)
    at net.minecraft.commands.Commands.performCommand(Commands.java:332)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(Blockab

### To Reproduce

Link chests restart server and plugin breaks

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
