### ISSUE TITLE
I think that when players try to sell heads through auto sell chests, this error happens.

### ISSUE THREAD

**Issue by FourNineRugz** [BG-Software-LLC/WildChests#99]
### Minecraft's Version

This server is running Purpur version git-Purpur-1523 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: c672eea on HEAD)
You are 10 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous version: git-Purpur-1506 (MC: 1.18.1)

### Plugin's Version

2.2.3

### Describe the bug

[02:29:52 ERROR]: BlockEntity threw exception at world:-16940,21,-12464
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()"
        at com.bgsoftware.wildchests.hooks.PricesProvider_EconomyShopGUI.getPrice(PricesProvider_EconomyShopGUI.java:20) ~[WildChests-2.2.3.jar:?]
        at com.bgsoftware.wildchests.handlers.ProvidersHandler.getPrice(ProvidersHandler.java:84) ~[WildChests-2.2.3.jar:?]
        at com.bgsoftware.wildchests.handlers.ProvidersHandler.canSellItem(ProvidersHandler.java:104) ~[WildChests-2.2.3.jar:?]
        at com.bgsoftware.wildchests.utils.ChestUtils.trySellItem(ChestUtils.java:119) ~[WildChests-2.2.3.jar:?]
        at com.bgsoftware.wildchests.utils.ChestUtils.lambda$trySellChest$1(ChestUtils.java:106) ~[WildChests-2.2.3.jar:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at com.bgsoftware.wildchests.utils.ChestUtils.trySellChest(ChestUtils.java:104) ~[WildChests-2.2.3.jar:?]
        at com.bgsoftware.wildchests.nms.NMSInventory_v1_18_R1$TileEntityWildChest.tick(NMSInventory_v1_18_R1.java:362) ~[WildChests-2.2.3.jar:?]
        at com.bgsoftware.wildchests.nms.NMSInventory_v1_18_R1$TileEntityWildChest.tick(NMSInventory_v1_18_R1.java:168) ~[WildChests-2.2.3.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1180) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1104) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:718) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1635) ~[purpur-1.18.1.jar:git-Purpur-1523]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1523]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1523]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1523]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1523]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

I think that when players try to sell heads through auto sell chests, this error happens.

### To Reproduce

I think that when players try to sell heads through auto sell chests, this error happens.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
